# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 12:30
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvd_portal', '0017_auto_20180702_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInChikitsaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorInChikitsaData', to='cvd_portal.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('medicine_Image', models.TextField()),
                ('compunds', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientInChikitsaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_faced', models.TextField()),
                ('next_visit', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('doctor_comments', models.TextField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientInChikitsaData', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderDataForParticularMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.IntegerField()),
                ('number_of_times_to_take_day', models.IntegerField()),
                ('number_of_times_to_take_week', models.IntegerField()),
                ('timings_of_intake', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('time_gap', models.DecimalField(decimal_places=1, max_digits=2)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medRemData', to='cvd_portal.Patient')),
            ],
        ),
    ]
