# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-03 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0017_auto_20180702_1800'),
        ('medicine_reminder', '0003_auto_20180703_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationInChikitsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_info_by_doc', models.TextField()),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifInChikitsa', to='cvd_portal.Notifications')),
            ],
        ),
        migrations.RemoveField(
            model_name='reminderdataforparticularmed',
            name='medicine_id',
        ),
        migrations.AddField(
            model_name='reminderdataforparticularmed',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_reminder.Medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reminderdataforparticularmed',
            name='number_of_times_to_take_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reminderdataforparticularmed',
            name='number_of_times_to_take_week',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
